apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: guestbook-canary
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-canary
  strategy:
    canary:
      maxSurge: 2
      maxUnavailable: 0
      steps:
      - setWeight: 20
      - pause:
          duration: 120
      - setWeight: 50
      - pause:
          duration: 120
  template:
    metadata:
      labels:
        app: guestbook-canary
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: guestbook-canary
        ports:
        - containerPort: 80
