apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: guestbook-bg
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-bg
  strategy:
    blueGreen:
      activeService: guestbook-bg
      previewService: guestbook-bg-prev
      scaleDownDelaySeconds: 60
  template:
    metadata:
      labels:
        app: guestbook-bg
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: guestbook-bg
        ports:
        - containerPort: 80
