---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-bg
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-bg
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-bg-prev
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-bg-prev
